import { SymbolCandidate } from './types';

export const THICKNESS_MAP = {
  thin: 2,
  medium: 4,
  thick: 6,
};

export const MAX_HISTORY = 50;
export const RECOGNITION_DELAY = 500;
export const STROKE_SPLIT_THRESHOLD = 300;
export const RESAMPLE_POINTS = 50;
export const SMOOTHING_WINDOW = 3;
export const NORMALIZE_SIZE = 64;

export const SYMBOL_CATEGORIES: SymbolCandidate[] = [
  { label: '0', latex: '0', probability: 0 },
  { label: '1', latex: '1', probability: 0 },
  { label: '2', latex: '2', probability: 0 },
  { label: '3', latex: '3', probability: 0 },
  { label: '4', latex: '4', probability: 0 },
  { label: '5', latex: '5', probability: 0 },
  { label: '6', latex: '6', probability: 0 },
  { label: '7', latex: '7', probability: 0 },
  { label: '8', latex: '8', probability: 0 },
  { label: '9', latex: '9', probability: 0 },
  { label: 'a', latex: 'a', probability: 0 },
  { label: 'b', latex: 'b', probability: 0 },
  { label: 'c', latex: 'c', probability: 0 },
  { label: 'd', latex: 'd', probability: 0 },
  { label: 'e', latex: 'e', probability: 0 },
  { label: 'f', latex: 'f', probability: 0 },
  { label: 'g', latex: 'g', probability: 0 },
  { label: 'h', latex: 'h', probability: 0 },
  { label: 'i', latex: 'i', probability: 0 },
  { label: 'j', latex: 'j', probability: 0 },
  { label: 'k', latex: 'k', probability: 0 },
  { label: 'l', latex: 'l', probability: 0 },
  { label: 'm', latex: 'm', probability: 0 },
  { label: 'n', latex: 'n', probability: 0 },
  { label: 'o', latex: 'o', probability: 0 },
  { label: 'p', latex: 'p', probability: 0 },
  { label: 'q', latex: 'q', probability: 0 },
  { label: 'r', latex: 'r', probability: 0 },
  { label: 's', latex: 's', probability: 0 },
  { label: 't', latex: 't', probability: 0 },
  { label: 'u', latex: 'u', probability: 0 },
  { label: 'v', latex: 'v', probability: 0 },
  { label: 'w', latex: 'w', probability: 0 },
  { label: 'x', latex: 'x', probability: 0 },
  { label: 'y', latex: 'y', probability: 0 },
  { label: 'z', latex: 'z', probability: 0 },
  { label: 'A', latex: 'A', probability: 0 },
  { label: 'B', latex: 'B', probability: 0 },
  { label: 'C', latex: 'C', probability: 0 },
  { label: 'D', latex: 'D', probability: 0 },
  { label: 'E', latex: 'E', probability: 0 },
  { label: 'F', latex: 'F', probability: 0 },
  { label: 'G', latex: 'G', probability: 0 },
  { label: 'H', latex: 'H', probability: 0 },
  { label: 'I', latex: 'I', probability: 0 },
  { label: 'J', latex: 'J', probability: 0 },
  { label: 'K', latex: 'K', probability: 0 },
  { label: 'L', latex: 'L', probability: 0 },
  { label: 'M', latex: 'M', probability: 0 },
  { label: 'N', latex: 'N', probability: 0 },
  { label: 'O', latex: 'O', probability: 0 },
  { label: 'P', latex: 'P', probability: 0 },
  { label: 'Q', latex: 'Q', probability: 0 },
  { label: 'R', latex: 'R', probability: 0 },
  { label: 'S', latex: 'S', probability: 0 },
  { label: 'T', latex: 'T', probability: 0 },
  { label: 'U', latex: 'U', probability: 0 },
  { label: 'V', latex: 'V', probability: 0 },
  { label: 'W', latex: 'W', probability: 0 },
  { label: 'X', latex: 'X', probability: 0 },
  { label: 'Y', latex: 'Y', probability: 0 },
  { label: 'Z', latex: 'Z', probability: 0 },
  { label: 'alpha', latex: '\\alpha', probability: 0 },
  { label: 'beta', latex: '\\beta', probability: 0 },
  { label: 'gamma', latex: '\\gamma', probability: 0 },
  { label: 'delta', latex: '\\delta', probability: 0 },
  { label: 'epsilon', latex: '\\epsilon', probability: 0 },
  { label: 'theta', latex: '\\theta', probability: 0 },
  { label: 'lambda', latex: '\\lambda', probability: 0 },
  { label: 'mu', latex: '\\mu', probability: 0 },
  { label: 'pi', latex: '\\pi', probability: 0 },
  { label: 'sigma', latex: '\\sigma', probability: 0 },
  { label: 'omega', latex: '\\omega', probability: 0 },
  { label: 'phi', latex: '\\phi', probability: 0 },
  { label: 'psi', latex: '\\psi', probability: 0 },
  { label: 'rho', latex: '\\rho', probability: 0 },
  { label: 'tau', latex: '\\tau', probability: 0 },
  { label: 'nu', latex: '\\nu', probability: 0 },
  { label: 'xi', latex: '\\xi', probability: 0 },
  { label: 'eta', latex: '\\eta', probability: 0 },
  { label: 'zeta', latex: '\\zeta', probability: 0 },
  { label: 'kappa', latex: '\\kappa', probability: 0 },
  { label: '+', latex: '+', probability: 0 },
  { label: '-', latex: '-', probability: 0 },
  { label: '*', latex: '\\times', probability: 0 },
  { label: '/', latex: '/', probability: 0 },
  { label: '=', latex: '=', probability: 0 },
  { label: 'neq', latex: '\\neq', probability: 0 },
  { label: 'approx', latex: '\\approx', probability: 0 },
  { label: 'pm', latex: '\\pm', probability: 0 },
  { label: '>', latex: '>', probability: 0 },
  { label: '<', latex: '<', probability: 0 },
  { label: 'geq', latex: '\\geq', probability: 0 },
  { label: 'leq', latex: '\\leq', probability: 0 },
  { label: 'in', latex: '\\in', probability: 0 },
  { label: 'subset', latex: '\\subset', probability: 0 },
  { label: '(', latex: '(', probability: 0 },
  { label: ')', latex: ')', probability: 0 },
  { label: '[', latex: '[', probability: 0 },
  { label: ']', latex: ']', probability: 0 },
  { label: '{', latex: '\\{', probability: 0 },
  { label: '}', latex: '\\}', probability: 0 },
  { label: 'sqrt', latex: '\\sqrt', probability: 0 },
  { label: 'int', latex: '\\int', probability: 0 },
  { label: 'sum', latex: '\\sum', probability: 0 },
  { label: 'prod', latex: '\\prod', probability: 0 },
  { label: 'partial', latex: '\\partial', probability: 0 },
  { label: 'infty', latex: '\\infty', probability: 0 },
  { label: 'lim', latex: '\\lim', probability: 0 },
  { label: 'rightarrow', latex: '\\rightarrow', probability: 0 },
  { label: 'leftarrow', latex: '\\leftarrow', probability: 0 },
  { label: 'leftrightarrow', latex: '\\leftrightarrow', probability: 0 },
  { label: 'fraction', latex: '\\frac', probability: 0 },
  { label: '^', latex: '^', probability: 0 },
  { label: '_', latex: '_', probability: 0 },
  { label: '.', latex: '.', probability: 0 },
  { label: ',', latex: ',', probability: 0 },
  { label: '!', latex: '!', probability: 0 },
];

export const getLatexForLabel = (label: string): string => {
  const symbol = SYMBOL_CATEGORIES.find(s => s.label === label);
  return symbol?.latex || label;
};
